import Providers from "@/config/Providers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Box } from "@mui/material";
import StarField from "./components/ParticleAnimation/StarField";



const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  // weight: "600",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KathFOSS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
<body className={`${poppins.variable} antialiased`}>

        <Providers>
          <StarField/>
          <Box sx={{ position: "relative", zIndex: 1 }}>{children}</Box>
        </Providers>
      </body>
    </html>
  );
}